// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_halowSetting_halowDebugTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_height(ui_halowSetting_halowDebugTextArea, 1052);
    lv_obj_set_width(ui_halowSetting_halowDebugTextArea, lv_pct(100));
    lv_obj_set_align(ui_halowSetting_halowDebugTextArea, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_halowSetting_halowDebugTextArea, 20000);
    lv_textarea_set_placeholder_text(ui_halowSetting_halowDebugTextArea, "Placeholder...");
    lv_obj_set_style_text_font(ui_halowSetting_halowDebugTextArea, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    // ui_Container1 = lv_obj_create(ui_Screen1);
    // lv_obj_remove_style_all(ui_Container1);
    // lv_obj_set_width(ui_Container1, lv_pct(100));
    // lv_obj_set_height(ui_Container1, lv_pct(50));
    // lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    // lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    // lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_pad_row(ui_Container1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Button1 = lv_btn_create(ui_Container1);
    // lv_obj_set_width(ui_Button1, 400);
    // lv_obj_set_height(ui_Button1, 85);
    // lv_obj_set_x(ui_Button1, -18);
    // lv_obj_set_y(ui_Button1, -524);
    // lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Label1 = lv_label_create(ui_Button1);
    // lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label1, "AT+MODE=ap");
    // lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Button3 = lv_btn_create(ui_Container1);
    // lv_obj_set_width(ui_Button3, 400);
    // lv_obj_set_height(ui_Button3, 85);
    // lv_obj_set_x(ui_Button3, -15);
    // lv_obj_set_y(ui_Button3, -339);
    // lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Label3 = lv_label_create(ui_Button3);
    // lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label3, "AT+MODE=sta");
    // lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Button4 = lv_btn_create(ui_Container1);
    // lv_obj_set_width(ui_Button4, 400);
    // lv_obj_set_height(ui_Button4, 85);
    // lv_obj_set_x(ui_Button4, -18);
    // lv_obj_set_y(ui_Button4, -524);
    // lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Label4 = lv_label_create(ui_Button4);
    // lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label4, "AT+WNBCFG");
    // lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
